-- 1. Table: bookings
CREATE TABLE public.bookings (
    booking_id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    display_name TEXT,
    field_no INTEGER,
    booking_date DATE,
    time_from TIME,
    time_to TIME,
    duration_minutes NUMERIC, -- Use numeric to support partial hours (e.g. 1.5) if needed
    crosses_18 BOOLEAN,
    price_total_thb NUMERIC,
    status TEXT,
    hold_expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    confirmed_by TEXT,
    cancelled_by TEXT,
    cancel_reason TEXT,
    paid_at TIMESTAMPTZ,
    version INTEGER,
    start_ts TIMESTAMPTZ,
    end_ts TIMESTAMPTZ,
    timeout_notified BOOLEAN,
    notes TEXT,
    admin_note TEXT
);

-- 2. Table: user_states
CREATE TABLE public.user_states (
    user_id TEXT PRIMARY KEY,
    selected_date DATE,
    selected_time TIME,
    duration_h NUMERIC,
    field_no INTEGER,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Table: logs
CREATE TABLE public.logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ,
    user_id TEXT,
    source_type TEXT,
    event_type TEXT,
    action TEXT,
    step TEXT,
    label TEXT,
    message_text TEXT,
    postback_data TEXT,
    process_ms INTEGER,
    extra_json JSONB,
    date_int INTEGER
);

-- Enable Row Level Security (RLS) - Optional for initial setup but recommended
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_states ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;

-- Create policies to allow public access (Since we are using Anon key for now and need to migrate data)
-- WARNING: This is for development/migration. You should tighten these later.
CREATE POLICY "Enable read/write for all users" ON public.logs FOR ALL USING (true) WITH CHECK (true);

-- 4. Table: profiles
CREATE TABLE IF NOT EXISTS public.profiles (
    user_id TEXT PRIMARY KEY,
    team_name TEXT,
    phone_number TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read/write for all users" ON public.profiles FOR ALL USING (true) WITH CHECK (true);


-- 5. Table: affiliates
CREATE TABLE IF NOT EXISTS public.affiliates (
    user_id TEXT PRIMARY KEY,
    referral_code TEXT UNIQUE,
    status TEXT DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED
    total_referrals INTEGER DEFAULT 0,
    total_earnings NUMERIC DEFAULT 0,
    bank_name TEXT,
    bank_account_no TEXT,
    student_card_url TEXT,
    school_name TEXT,
    birth_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.affiliates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for everyone" ON public.affiliates FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON public.affiliates FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for owners" ON public.affiliates FOR UPDATE USING (auth.uid()::text = user_id);

-- 6. Table: referrals
CREATE TABLE IF NOT EXISTS public.referrals (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    referrer_id TEXT,
    referee_id TEXT,
    booking_id TEXT,
    status TEXT DEFAULT 'PENDING_PAYMENT', -- PENDING_PAYMENT, COMPLETED
    reward_amount NUMERIC DEFAULT 100,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for everyone" ON public.referrals FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated" ON public.referrals FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for service role" ON public.referrals FOR UPDATE USING (true);

-- 7. Table: referral_programs
CREATE TABLE IF NOT EXISTS public.referral_programs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT,
    is_active BOOLEAN DEFAULT true,
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,
    discount_percent INTEGER,
    reward_amount INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.referral_programs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for everyone" ON public.referral_programs FOR SELECT USING (true);
