-- 1. FIELDS TABLE (Stores field configuration)
CREATE TABLE public.fields (
    id SERIAL PRIMARY KEY,
    label TEXT NOT NULL,
    type TEXT NOT NULL,
    matchday_court_id INT,
    active BOOLEAN DEFAULT TRUE,
    price_pre INT NOT NULL,
    price_post INT NOT NULL
);

-- Seed Initial Data (from field_config.gs)
INSERT INTO public.fields (id, label, type, matchday_court_id, active, price_pre, price_post) VALUES
(1, 'สนาม #1', '5 คน',   2424, true, 500, 700),
(2, 'สนาม #2', '5 คน',   2425, true, 500, 700),
(3, 'สนาม #3', '7-8 คน', 2428, true, 1000, 1200),
(4, 'สนาม #4', '7 คน',   2426, true, 800, 1000),
(5, 'สนาม #5', '7 คน',   2427, true, 800, 1000),
(6, 'สนาม #6 ใหม่', '7 คน', 2429, true, 1000, 1200);

-- 2. BOOKINGS TABLE (Stores booking history)
CREATE TABLE public.bookings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id TEXT UNIQUE, -- Optional custom ID like "BK001"
    user_id TEXT NOT NULL,
    display_name TEXT,
    field_no INT REFERENCES public.fields(id),
    date DATE NOT NULL,
    time_from TIME NOT NULL,
    time_to TIME NOT NULL,
    duration_h NUMERIC(3, 1) NOT NULL,
    crosses_18 BOOLEAN DEFAULT FALSE,
    price_total_thb INT NOT NULL,
    status TEXT DEFAULT 'PENDING', -- 'PENDING', 'CONFIRMED', 'CANCELLED'
    
    -- Additional metadata from your CSV
    hold_expires_at TIMESTAMPTZ,
    confirmed_by TEXT,
    cancelled_by TEXT,
    cancel_reason TEXT,
    paid_at TIMESTAMPTZ,
    notes TEXT,
    admin_note TEXT,
    
    version INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for faster search by date and user
CREATE INDEX idx_bookings_date ON public.bookings(date);
CREATE INDEX idx_bookings_user_id ON public.bookings(user_id);

-- 3. USER_STATE TABLE (Stores conversation state)
CREATE TABLE public.user_state (
    user_id TEXT PRIMARY KEY,
    date DATE,
    time_from TEXT,
    duration_h NUMERIC(3, 1),
    field_no INT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Using JSONB for flexibility if we add more steps later
    state_data JSONB DEFAULT '{}'::jsonb
);

-- 4. SYSTEM_LOGS TABLE (Stores usage stats)
CREATE TABLE public.system_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TIMESTAMPTZ DEFAULT NOW(),
    user_id TEXT,
    source_type TEXT, -- 'user', 'system'
    event_type TEXT,  -- 'message', 'postback'
    action TEXT,
    step TEXT,
    label TEXT,
    message_text TEXT,
    postback_data TEXT,
    process_ms INT,
    extra_json JSONB
);

-- Enable Row Level Security (RLS) - Optional for now but good practice
ALTER TABLE public.fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public read access to fields (so everyone can see prices)
CREATE POLICY "Public fields are viewable by everyone" ON public.fields FOR SELECT USING (true);

-- Policy: Service Role (our Edge Function) has full access
-- (Supabase Service Role bypasses RLS by default, so we don't strictly need more policies for the bot)
