-- Create promo_campaigns table (Mother Table)
CREATE TABLE IF NOT EXISTS public.promo_campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  discount_type VARCHAR(10) NOT NULL CHECK (discount_type IN ('percent', 'fixed')),
  discount_value NUMERIC NOT NULL,
  min_spent NUMERIC DEFAULT 0,
  max_discount NUMERIC, -- Only relevant for 'percent'
  total_quota INTEGER DEFAULT 100,
  used_count INTEGER DEFAULT 0,
  start_date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ NOT NULL,
  eligible_fields INTEGER[], -- Array of field IDs, null means all fields
  keyword VARCHAR(50) UNIQUE, -- If triggered by keyword
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  updated_by TEXT
);

-- Create user_vouchers table (User Wallet)
CREATE TABLE IF NOT EXISTS public.user_vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL, -- LINE User ID
  campaign_id BIGINT REFERENCES public.promo_campaigns(id) ON DELETE CASCADE,
  status VARCHAR(20) DEFAULT 'available' CHECK (status IN ('available', 'used', 'expired')),
  claimed_at TIMESTAMPTZ DEFAULT NOW(),
  used_at TIMESTAMPTZ,
  booking_id TEXT, -- Reference to the final booking
  
  -- Prevent user from claiming the same campaign multiple times if not allowed
  UNIQUE(user_id, campaign_id)
);

-- Enable RLS
ALTER TABLE public.promo_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_vouchers ENABLE ROW LEVEL SECURITY;

-- Policies (Development: Allow all)
CREATE POLICY "Enable read/write for all users" ON public.promo_campaigns FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable read/write for all users" ON public.user_vouchers FOR ALL USING (true) WITH CHECK (true);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_user_vouchers_user_id ON public.user_vouchers(user_id);
CREATE INDEX IF NOT EXISTS idx_promo_campaigns_dates ON public.promo_campaigns(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_promo_campaigns_keyword ON public.promo_campaigns(keyword);

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_promo_campaigns_updated_at
    BEFORE UPDATE ON public.promo_campaigns
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();
