-- Add role column to profiles
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS role VARCHAR(20) DEFAULT 'member';

-- Create manual_promo_codes table
CREATE TABLE IF NOT EXISTS manual_promo_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    discount_type TEXT NOT NULL CHECK (discount_type IN ('percent', 'fixed')),
    discount_value DECIMAL(10, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'expired')),
    min_price DECIMAL(10, 2) DEFAULT 0,
    max_discount DECIMAL(10, 2),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id)
);

-- Enable RLS
ALTER TABLE manual_promo_codes ENABLE ROW LEVEL SECURITY;

-- Policies for manual_promo_codes

-- 1. Allow Service Role full access (for Bot / Backend)
CREATE POLICY "Allow service role full access" ON manual_promo_codes
    FOR ALL
    USING (auth.role() = 'service_role');

-- 2. Allow Authenticated Users (Admins) full access
-- Note: In a real app, strict admin check is recommended. 
-- For this project, we assume authenticated users are admins or authorized.
CREATE POLICY "Allow authenticated full access" ON manual_promo_codes
    FOR ALL
    USING (auth.role() = 'authenticated');

-- 3. Public access is DENIED by default (no policy = no access for anon)
