-- Create promo_codes table
CREATE TABLE IF NOT EXISTS public.promo_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(6) UNIQUE NOT NULL,
  user_id TEXT NOT NULL,
  field_id INTEGER NOT NULL,
  booking_date DATE NOT NULL,
  time_from TIME NOT NULL,
  time_to TIME NOT NULL,
  duration_h NUMERIC NOT NULL,
  original_price NUMERIC NOT NULL,
  discount_type VARCHAR(10) NOT NULL,
  discount_value NUMERIC NOT NULL,
  discount_amount NUMERIC NOT NULL,
  final_price NUMERIC NOT NULL,
  status VARCHAR(20) DEFAULT 'active',
  expires_at TIMESTAMPTZ NOT NULL,
  booking_id TEXT,
  used_at TIMESTAMPTZ,
  used_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  notes TEXT
);

-- Enable RLS for promo_codes
ALTER TABLE public.promo_codes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read/write for all users" ON public.promo_codes FOR ALL USING (true) WITH CHECK (true);

-- Create promo_settings table
CREATE TABLE IF NOT EXISTS public.promo_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enabled BOOLEAN DEFAULT true,
  discount_type VARCHAR(10) DEFAULT 'percent',
  discount_value NUMERIC DEFAULT 10,
  min_booking_price NUMERIC DEFAULT 500,
  expiry_minutes INTEGER DEFAULT 30,
  daily_limit_per_user INTEGER DEFAULT 2,
  reuse_window_hours INTEGER DEFAULT 2,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  updated_by TEXT
);

-- Enable RLS for promo_settings
ALTER TABLE public.promo_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read/write for all users" ON public.promo_settings FOR ALL USING (true) WITH CHECK (true);

-- Insert default settings
INSERT INTO public.promo_settings (id, enabled, discount_type, discount_value, min_booking_price, expiry_minutes, daily_limit_per_user, reuse_window_hours)
VALUES (1, true, 'percent', 10, 500, 30, 2, 2)
ON CONFLICT (id) DO NOTHING;
